### ISSUE TITLE
Code contribution of a pair of projects

### ISSUE THREAD

**Issue by hectorlf** [PebbleTemplates/pebble-spring3#6]
I've been working lately on integrating Pebble with some other frameworks and I'd like to contribute the code of 2 of them: a Spring Boot starter and a Spring Security extension. Contribute meaning that I'd use your packagery and disclaimers in the code and you'd take complete control over it via fork or something alike (with my voluteering to maintain them).

Why? Because I realized something: third party projects are good enough for little utilities or something specific, but support for the top 5 frameworks should be something "official" to be visible and not be scary. For example, this morning someone pointed out to me another boot starter for Pebble that I was unaware of, because I didn't find it on github search.

With this 2 and some work that's needed in pebble-spring3, the support level should be mostly on par to what Thymeleaf offers.

What do you think?

**Comment by mbosecke** [comment]
That sounds like an interesting idea. I'm actually debating the idea of setting up a new github "organization" account that will become the new dedicated home of Pebble and no longer use my personal account. It looks like we'll be able to transfer ownership of our existing repositories to this new account. It also looks like I can give you the ability to continue maintaining the two repositories without my intervention. How does that sound?

**Comment by hectorlf** [comment]
Honestly, I'm good with whatever route you choose :+1:

**Comment by mbosecke** [comment]
I moved all of the official pebble repositories into a new github account and if the offer still stands, I'd like to move some of your repositories into this account as well. Afterwards, I'd like to set you up with the correct permissions so that you can continue to maintain those repositories without my intervention.  How does that sound?

**Comment by hectorlf** [comment]
Awesome, thank you!! I'll start repackaging and mavenizing right now, and I'll transfer the projects as they are ready. This leads me to the next question: what about releases? I don't have a maven central account so I'm a newbie to the process, but I'm guessing every artifact hanging from the com.mitchellbosecke.pebble needs to be signed with your private key, right?

**Comment by hectorlf** [comment]
GitHub tells me that I don't have admin rights on PebbleTemplates and so cannot transfer a project there. Shall we try the forking way? This one is ready: https://github.com/hectorlf/pebble-spring-boot-starter

**Comment by mbosecke** [comment]
Sorry, bear with me. I've invited you to be a member of the organization; hopefully that will be enough to transfer ownership. Then I'll have to fiddle with permissions so that you maintain write access to the repo.

And yes I'll have to deal with releases but that's fine with me.

**Comment by hectorlf** [comment]
I'm in, thank you! But still getting the same message: "You don’t have admin rights to PebbleTemplates" :(

**Comment by mbosecke** [comment]
Try again! If it still doesn't work I still have one more idea.

**Comment by hectorlf** [comment]
Just tried, still no luck :_(

**Comment by mbosecke** [comment]
I contacted github support and it turns out their documentation on the matter is completely outdated and wrong. They explained the actual method to me so I'm 99.9% sure it will work this time, try once more!

**Comment by hectorlf** [comment]
What an insanely hard process, but yay!! It's alive!! Thank you!!
