### ISSUE TITLE
How to setup pebble in spring config xml

### ISSUE THREAD

**Issue by ablipan** [PebbleTemplates/pebble-spring3#7]
How can i setup PebbleViewResolver in spring config xml.
```xml
<bean class="com.mitchellbosecke.pebble.spring.PebbleViewResolver">
    <property name="pebbleEngine" ref=""/><!-- how to config this value -->
</bean>
```

**Comment by hectorlf** [comment]
You need a little workaround:
- write an EngineFactory class (see the attached file and modify it to your liking)
- define a bean in the xml with this syntax:
`<bean id="pebbleEngine"
    class="com.mitchellbosecke.pebble.spring.PebbleEngineFactory"
    factory-method="instance"/>`

If you'd like to define the Loader instance also in XML, you need a bit more code. Just let me know :+1: 
[PebbleEngineFactory.java.txt](https://github.com/mbosecke/pebble-spring3/files/134580/PebbleEngineFactory.java.txt)

**Comment by ablipan** [comment]
There is already a `InternalResourceViewResolver` which directing to `*.jsp` files  in my project, i didn't find a compatible way to work with `pebble-spring3`(I'm new to spring ...). But i finally use the `response.getWriter().write()` to render the `*.peb` files.

**Comment by hectorlf** [comment]
Spring view resolvers work in chain: you can define as many as you want and they will be tried one after another until one is found that can process the request. The only thing you need to ensure is that the PebbleViewResolver sits higher in the chain than InternalViewResolver, and that's done with the "order" property.

See this: http://www.mkyong.com/spring-mvc/configure-multiple-view-resolvers-priority-in-spring-mvc/

**Comment by ebussieres** [comment]
I've just created a new example in project https://github.com/PebbleTemplates/pebble-example-spring for a spring project using a xml configuration
